{
  "deprecated": true,
  "cpeName": "cpe:2.3:a:python:python:3.5:*:*:*:*:*:*:*",
  "cpeNameId": "5F9475E4-6266-4C44-9539-F1B2EB7F1BA2",
  "created": "2017-11-30T15:38:25.743",
  "lastModified": "2021-01-06T16:09:30.627",
  "titles": [
    {
      "title": "Python 3.5",
      "lang": "en"
    }
  ],
  "refs": [
    {
      "ref": "https://bugs.python.org/issue27850",
      "type": "Advisory"
    },
    {
      "ref": "https://www.python.org/",
      "type": "Vendor"
    }
  ],
  "deprecatedBy": [
    {
      "cpeName": "cpe:2.3:a:python:python:3.5.0:-:*:*:*:*:*:*",
      "cpeNameId": "3A121C1D-90EF-48E0-9FB3-8A13077659DF"
    }
  ]
}
