{
	"deprecated": true,
	"cpeName": "cpe:2.3:a:python:python:3.9.1:*:*:*:*:*:*:*",
	"cpeNameId": "C25A5C86-CC32-4A0C-97FA-6EE2157D90CF",
	"created": "2021-01-22T19:35:47.257",
	"lastModified": "2022-06-30T15:44:22.590",
	"titles": [
		{
			"title": "Python 3.9.1",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://bugs.python.org/issue42938",
			"type": "Advisory"
		},
		{
			"ref": "https://github.com/python/cpython/pull/24239",
			"type": "Advisory"
		},
		{
			"ref": "https://github.com/CVEProject/cvelist/blob/master/2021/3xxx/CVE-2021-3177.json",
			"type": "Advisory"
		}
	],
	"deprecatedBy": [
		{
			"cpeName": "cpe:2.3:a:python:python:3.9.1:-:*:*:*:*:*:*",
			"cpeNameId": "7A14D518-226F-440E-949A-D3A10D790872"
		}
	]
}
