{
  "deprecated": false,
  "cpeName": "cpe:2.3:a:ibm:datapower_gateway:2018.4.1.12:*:*:*:*:*:*:*",
  "cpeNameId": "D7566F22-3967-4929-A37D-E5783131DF1E",
  "created": "2020-09-23T17:55:21.157",
  "lastModified": "2020-09-23T17:55:21.157",
  "titles": [
    {
      "title": "IBM DataPower Gateway 2018.4.1.12",
      "lang": "en"
    }
  ],
  "refs": [
    {
      "ref": "https://www.ibm.com/products/datapower-gateway",
      "type": "Product"
    },
    {
      "ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/184439",
      "type": "Advisory"
    }
  ]
}
